# file for testing API with VSCode extension `REST Client` by **Huachao Mao**
#     https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# tutorial found on Medium:
#     https://medium.com/lseg-developer-community/how-to-test-rest-api-with-visual-studio-code-rest-client-extensions-9f2e061d0299

@hostname = localhost
@PORT = 3000
@baseUrl = http://{{hostname}}:{{PORT}}
@api = api
@vers = v1

###

GET {{baseUrl}}/

###

POST {{baseUrl}}/

### get all tours

GET {{baseUrl}}/{{api}}/{{vers}}/tours

### get specific tour by id

GET {{baseUrl}}/{{api}}/{{vers}}/tours/5

### get specific tour by _id MONGO

GET {{baseUrl}}/{{api}}/{{vers}}/tours/663403e65bed1a47a6b747fc

### get specific tour by id NOT FOUND

GET {{baseUrl}}/{{api}}/{{vers}}/tours/555

### create new tour

POST {{baseUrl}}/{{api}}/{{vers}}/tours
Content-Type: application/json

{
  "name": "Test tour",
  "duration": 10,
  "difficulty": "easy",
  "price": 400
}

### create new tour WITHOUT PRICE

POST {{baseUrl}}/{{api}}/{{vers}}/tours
Content-Type: application/json

{
  "name": "Test tour",
  "duration": 10,
  "difficulty": "easy"
}

### update a tour field

PATCH {{baseUrl}}/{{api}}/{{vers}}/tours/3
Content-Type: application/json

{
  "duration": 5
}
### update specific field of invalid ID, NOT FOUND

PATCH {{baseUrl}}/{{api}}/{{vers}}/tours/555
Content-Type: application/json

{
  "duration": 5
}

### update a tour field

DELETE {{baseUrl}}/{{api}}/{{vers}}/tours/9

### update specific field of invalid ID, NOT FOUND

DELETE {{baseUrl}}/{{api}}/{{vers}}/tours/555

### get all users

GET {{baseUrl}}/{{api}}/{{vers}}/users

### create new user

# TODO : Not Yet Implemented
POST {{baseUrl}}/{{api}}/{{vers}}/users

###
